from django.conf.urls import url
from applications.director.views import *

urlpatterns = [
# Director url    
    url(r'^sez/$', SezView.as_view(), name = 'sez'),
    url(r'^sez/(?P<date>[0-9]+)/$', SezView.as_view(), name = 'sudalgaa'),
    

    url(r'^tsalin/$', TsalinFormView.as_view(), name = 'tsalin'),
    url(r'^hereglegch/$', HereglegchFormview.as_view(), name = 'hereglegch'),
    url(r'^ushudaldanavah/$', UsHudaldanAvahFormView.as_view(), name = 'ushudaldanavah'),
    url(r'^golchiinsuuriune/$', AANBFormView.as_view(), name = 'golchiinsuuriune'),
    url(r'^orlogo/$', OrlogoFormView.as_view(), name = 'orlogo'),
    url(r'^busadorlogo/$', BusadOrlogoFormView.as_view(), name = 'busadorlogo'),
    url(r'^golch/$', GolchFormView.as_view(), name = 'golch'),
    url(r'^golchhangagch/$', GolchHangagchFormView.as_view(), name = 'golchhangagch'),
    url(r'^tariff/$', TariffFormView.as_view(), name = 'tariff'),
    url(r'^zardal1/$', ZardalFormView1.as_view(), name = 'zardal1'),
    url(r'^zardal2/$', ZardalFormView2.as_view(), name = 'zardal2'),
    url(r'^zardal3/$', ZardalFormView3.as_view(), name = 'zardal3'),
    url(r'^zardal4/$', ZardalFormView4.as_view(), name = 'zardal4'),
    url(r'^zardal5/$', ZardalFormView5.as_view(), name = 'zardal5'),
    url(r'^zardal6/$', ZardalFormView6.as_view(), name = 'zardal6'),
    url(r'^zardal7/$', ZardalFormView7.as_view(), name = 'zardal7'),
    url(r'^zardal8/$', ZardalFormView8.as_view(), name = 'zardal8'),
    url(r'^zardal9/$', ZardalFormView9.as_view(), name = 'zardal9'),
    url(r'^zardal10/$', ZardalFormView10.as_view(), name = 'zardal10'),
    url(r'^zardal11/$', ZardalFormView11.as_view(), name = 'zardal11'),
    url(r'^zardal12/$', ZardalFormView12.as_view(), name = 'zardal12'),
    url(r'^zardal13/$', ZardalFormView13.as_view(), name = 'zardal13'),
    url(r'^zardal14/$', ZardalFormView14.as_view(), name = 'zardal14'),
    url(r'^zardal15/$', ZardalFormView15.as_view(), name = 'zardal15'),
    url(r'^zardal16/$', ZardalFormView16.as_view(), name = 'zardal16'),
    url(r'^zardal17/$', ZardalFormView17.as_view(), name = 'zardal17'),
    url(r'^zardal18/$', ZardalFormView18.as_view(), name = 'zardal18'),
    url(r'^zardal19/$', ZardalFormView19.as_view(), name = 'zardal19'),
    url(r'^sanalgomdol/$', SanalGomdolView.as_view(), name = 'sanalgomdol'),
    url(r'^tehniknohtsol/$', TehnikNohtsolView.as_view(), name = 'tehniknohtsol'),
    url(r'^tasaldal/$', TasaldalView.as_view(), name = 'tasaldal'),
    

    url(r'^tsalinlist/$', TsalinViewList.as_view(), name = 'tsalinlist'),
    url(r'^hereglegchlist/$', HereglegchFormviewList.as_view(), name = 'hereglegchlist'),
    url(r'^golchiinsuuriunelist/$', AANBFormViewList.as_view(), name = 'golchiinsuuriunelist'),
    url(r'^ushudaldanavahlist/$', UsHudaldanAvahFormViewList.as_view(), name = 'ushudaldanavahlist'),
    url(r'^golchlist/$', GolchFormViewList.as_view(), name = 'golchlist'),
    url(r'^tarifflist/$', TariffFormViewList.as_view(), name = 'tarifflist'),
    url(r'^golchhangagchlist/$', GolchHangagchFormViewList.as_view(), name = 'golchhangagchlist'),
    url(r'^orlogolist/$', OrlogoFormViewList.as_view(), name = 'orlogolist'),
    url(r'^busadorlogolist/$', BusadOrlogoFormViewList.as_view(), name = 'busadorlogolist'),
    url(r'^zardal1list/$', ZardalFormView1List.as_view(), name = 'zardal1list'),
    url(r'^zardal2list/$', ZardalFormView2List.as_view(), name = 'zardal2list'),
    url(r'^zardal3list/$', ZardalFormView3List.as_view(), name = 'zardal3list'),
    url(r'^zardal4list/$', ZardalFormView4List.as_view(), name = 'zardal4list'),
    url(r'^zardal5list/$', ZardalFormView5List.as_view(), name = 'zardal5list'),
    url(r'^zardal6list/$', ZardalFormView6List.as_view(), name = 'zardal6list'),
    url(r'^zardal7list/$', ZardalFormView7List.as_view(), name = 'zardal7list'),
    url(r'^zardal8list/$', ZardalFormView8List.as_view(), name = 'zardal8list'),
    url(r'^zardal9list/$', ZardalFormView9List.as_view(), name = 'zardal9list'),
    url(r'^zardal10list/$', ZardalFormView10List.as_view(), name = 'zardal10list'),
    url(r'^zardal11list/$', ZardalFormView11List.as_view(), name = 'zardal11list'),
    url(r'^zardal12list/$', ZardalFormView12List.as_view(), name = 'zardal12list'),
    url(r'^zardal13list/$', ZardalFormView13List.as_view(), name = 'zardal13list'),
    url(r'^zardal14list/$', ZardalFormView14List.as_view(), name = 'zardal14list'),
    url(r'^zardal15list/$', ZardalFormView15List.as_view(), name = 'zardal15list'),
    url(r'^zardal16list/$', ZardalFormView16List.as_view(), name = 'zardal16list'),
    url(r'^zardal17list/$', ZardalFormView17List.as_view(), name = 'zardal17list'),
    url(r'^zardal18list/$', ZardalFormView18List.as_view(), name = 'zardal18list'),
    url(r'^zardal19list/$', ZardalFormView19List.as_view(), name = 'zardal19list'),
    url(r'^sanalgomdollist/$', SanalGomdolViewList.as_view(), name = 'sanalgomdollist'),
    url(r'^tehniknohtsollist/$', TehnikNohtsolViewList.as_view(), name = 'tehniknohtsollist'),
    url(r'^tasaldallist/$', TasaldalViewList.as_view(), name = 'tasaldallist'),


    url(r'^tsalin/(?P<date>[0-9]+)/$', TsalinFormView.as_view(), name = 'tsalin'),
    url(r'^hereglegch/(?P<date>[0-9]+)/$', HereglegchFormview.as_view(), name = 'hereglegch'),
    url(r'^ushudaldanavah/(?P<date>[0-9]+)/$', UsHudaldanAvahFormView.as_view(), name = 'ushudaldanavah'),
    url(r'^golchiinsuuriune/(?P<date>[0-9]+)/$', AANBFormView.as_view(), name = 'golchiinsuuriune'),
    url(r'^orlogo/(?P<date>[0-9]+)/$', OrlogoFormView.as_view(), name = 'orlogo'),
    url(r'^busadorlogo/(?P<date>[0-9]+)/$', BusadOrlogoFormView.as_view(), name = 'busadorlogo'),
    url(r'^golch/(?P<date>[0-9]+)/$', GolchFormView.as_view(), name = 'golch'),
    url(r'^golchhangagch/(?P<date>[0-9]+)/$', GolchHangagchFormView.as_view(), name = 'golchhangagch'),
    url(r'^tariff/(?P<date>[0-9]+)/$', TariffFormView.as_view(), name = 'tariff'),
    url(r'^zardal1/(?P<date>[0-9]+)/$', ZardalFormView1.as_view(), name = 'zardal1'),
    url(r'^zardal2/(?P<date>[0-9]+)/$', ZardalFormView2.as_view(), name = 'zardal2'),
    url(r'^zardal3/(?P<date>[0-9]+)/$', ZardalFormView3.as_view(), name = 'zardal3'),
    url(r'^zardal4/(?P<date>[0-9]+)/$', ZardalFormView4.as_view(), name = 'zardal4'),
    url(r'^zardal5/(?P<date>[0-9]+)/$', ZardalFormView5.as_view(), name = 'zardal5'),
    url(r'^zardal6/(?P<date>[0-9]+)/$', ZardalFormView6.as_view(), name = 'zardal6'),
    url(r'^zardal7/(?P<date>[0-9]+)/$', ZardalFormView7.as_view(), name = 'zardal7'),
    url(r'^zardal8/(?P<date>[0-9]+)/$', ZardalFormView8.as_view(), name = 'zardal8'),
    url(r'^zardal9/(?P<date>[0-9]+)/$', ZardalFormView9.as_view(), name = 'zardal9'),
    url(r'^zardal10/(?P<date>[0-9]+)/$', ZardalFormView10.as_view(), name = 'zardal10'),
    url(r'^zardal11/(?P<date>[0-9]+)/$', ZardalFormView11.as_view(), name = 'zardal11'),
    url(r'^zardal12/(?P<date>[0-9]+)/$', ZardalFormView12.as_view(), name = 'zardal12'),
    url(r'^zardal13/(?P<date>[0-9]+)/$', ZardalFormView13.as_view(), name = 'zardal13'),
    url(r'^zardal14/(?P<date>[0-9]+)/$', ZardalFormView14.as_view(), name = 'zardal14'),
    url(r'^zardal15/(?P<date>[0-9]+)/$', ZardalFormView15.as_view(), name = 'zardal15'),
    url(r'^zardal16/(?P<date>[0-9]+)/$', ZardalFormView16.as_view(), name = 'zardal16'),
    url(r'^zardal17/(?P<date>[0-9]+)/$', ZardalFormView17.as_view(), name = 'zardal17'),
    url(r'^zardal18/(?P<date>[0-9]+)/$', ZardalFormView18.as_view(), name = 'zardal18'),
    url(r'^zardal19/(?P<date>[0-9]+)/$', ZardalFormView19.as_view(), name = 'zardal19'),
    url(r'^sanalgomdol/(?P<date>[0-9]+)/$', SanalGomdolView.as_view(), name = 'sanalgomdol'),
    url(r'^tehniknohtsol/(?P<date>[0-9]+)/$', TehnikNohtsolView.as_view(), name = 'tehniknohtsol'),
    url(r'^tasaldal/(?P<date>[0-9]+)/$', TasaldalView.as_view(), name = 'tasaldal'),


    url(r'^tsalinlist/(?P<date>[0-9]+)/$', TsalinViewList.as_view(), name = 'tsalinlist'),
    url(r'^hereglegchlist/(?P<date>[0-9]+)/$', HereglegchFormviewList.as_view(), name = 'hereglegchlist'),
    url(r'^golchiinsuuriunelist/(?P<date>[0-9]+)/$', AANBFormViewList.as_view(), name = 'golchiinsuuriunelist'),
    url(r'^ushudaldanavahlist/(?P<date>[0-9]+)/$', UsHudaldanAvahFormViewList.as_view(), name = 'ushudaldanavahlist'),
    url(r'^golchlist/(?P<date>[0-9]+)/$', GolchFormViewList.as_view(), name = 'golchlist'),
    url(r'^tarifflist/(?P<date>[0-9]+)/$', TariffFormViewList.as_view(), name = 'tarifflist'),
    url(r'^golchhangagchlist/(?P<date>[0-9]+)/$', GolchHangagchFormViewList.as_view(), name = 'golchhangagchlist'),
    url(r'^orlogolist/(?P<date>[0-9]+)/$', OrlogoFormViewList.as_view(), name = 'orlogolist'),
    url(r'^busadorlogolist/(?P<date>[0-9]+)/$', BusadOrlogoFormViewList.as_view(), name = 'busadorlogolist'),
    url(r'^zardal1list/(?P<date>[0-9]+)/$', ZardalFormView1List.as_view(), name = 'zardal1list'),
    url(r'^zardal2list/(?P<date>[0-9]+)/$', ZardalFormView2List.as_view(), name = 'zardal2list'),
    url(r'^zardal3list/(?P<date>[0-9]+)/$', ZardalFormView3List.as_view(), name = 'zardal3list'),
    url(r'^zardal4list/(?P<date>[0-9]+)/$', ZardalFormView4List.as_view(), name = 'zardal4list'),
    url(r'^zardal5list/(?P<date>[0-9]+)/$', ZardalFormView5List.as_view(), name = 'zardal5list'),
    url(r'^zardal6list/(?P<date>[0-9]+)/$', ZardalFormView6List.as_view(), name = 'zardal6list'),
    url(r'^zardal7list/(?P<date>[0-9]+)/$', ZardalFormView7List.as_view(), name = 'zardal7list'),
    url(r'^zardal8list/(?P<date>[0-9]+)/$', ZardalFormView8List.as_view(), name = 'zardal8list'),
    url(r'^zardal9list/(?P<date>[0-9]+)/$', ZardalFormView9List.as_view(), name = 'zardal9list'),
    url(r'^zardal10list/(?P<date>[0-9]+)/$', ZardalFormView10List.as_view(), name = 'zardal10list'),
    url(r'^zardal11list/(?P<date>[0-9]+)/$', ZardalFormView11List.as_view(), name = 'zardal11list'),
    url(r'^zardal12list/(?P<date>[0-9]+)/$', ZardalFormView12List.as_view(), name = 'zardal12list'),
    url(r'^zardal13list/(?P<date>[0-9]+)/$', ZardalFormView13List.as_view(), name = 'zardal13list'),
    url(r'^zardal14list/(?P<date>[0-9]+)/$', ZardalFormView14List.as_view(), name = 'zardal14list'),
    url(r'^zardal15list/(?P<date>[0-9]+)/$', ZardalFormView15List.as_view(), name = 'zardal15list'),
    url(r'^zardal16list/(?P<date>[0-9]+)/$', ZardalFormView16List.as_view(), name = 'zardal16list'),
    url(r'^zardal17list/(?P<date>[0-9]+)/$', ZardalFormView17List.as_view(), name = 'zardal17list'),
    url(r'^zardal18list/(?P<date>[0-9]+)/$', ZardalFormView18List.as_view(), name = 'zardal18list'),
    url(r'^zardal19list/(?P<date>[0-9]+)/$', ZardalFormView19List.as_view(), name = 'zardal19list'),
    url(r'^sanalgomdollist/(?P<date>[0-9]+)/$', SanalGomdolViewList.as_view(), name = 'sanalgomdollist'),
    url(r'^tehniknohtsollist/(?P<date>[0-9]+)/$', TehnikNohtsolViewList.as_view(), name = 'tehniknohtsollist'),
    url(r'^tasaldallist/(?P<date>[0-9]+)/$', TasaldalViewList.as_view(), name = 'tasaldallist'),



    url(r'^send/sariin_tailan/(?P<id>[0-9]+)/$', sendtailan, name = 'sendtailan'),
    url(r'^send/sudalgaa/(?P<id>[0-9]+)/$', sendsudalgaa, name = 'sendsudalgaa'),
    #url(r'^export/excel/example/$', Export, name = 'export'),



    url(r'^tailan/copy/(?P<id>[0-9]+)/(?P<tid>[0-9]+)/$', SezView.copy, name = 'copy'),

    url(r'^sariin_export/(?P<id>[0-9]+)/$', excel_export, name = 'sariin_export'),

]